feat: resolve task 1-map
antryabov/homework-js pull request #1
Opened 2024-03-06 19:00 UTC by antryabov

2024-03-10 19:01 UTC, Levitinn requested changes

2024-03-10 19:01 UTC, Levitinn commented on app.js
твой код не универсален. если у массива будут объекты с другими ИД, ничего не отработает. Так не годится.
во первых, попробуй сделать всю логику внутри одной функции, чтобы функция принимала любой массив объектов, и возвращала только массив без повторений по ИД

2024-03-11 04:32 UTC, antryabov commented on app.js
Привет, комментарии прочитал и доберусь до исправлений только завтра. Спасибо большое за ревью! 
Да, тут мне немного было непонятно, нужно ли сделать универсальный код, либо сделать как я. Исправлю все завтра.

2024-03-12 17:52 UTC, antryabov commented on app.js
Посидел сегодня немного и никак не могу решить. Я не прошу написать код и прочее, но не мог бы ты немного подсказать. Я все упираюсь в то, что в одном цикле я не найти дубликаты. Я думал, что можно в Set добавить только id и потом что-то с этим сделать...

2024-03-12 20:29 UTC, antryabov commented on app.js
> твой код не универсален. если у массива будут объекты с другими ИД, ничего не отработает. Так не годится. во первых, попробуй сделать всю логику внутри одной функции, чтобы функция принимала любой массив объектов, и возвращала только массив без повторений по ИД

Посидел сегодня немного и никак не могу решить. Я не прошу написать код и прочее, но не мог бы ты немного подсказать. Я все упираюсь в то, что в одном цикле я не могу найти дубликаты. Я думал, что можно в Set только id, чтобы не было дубликатов и потом что-то с этим сделать...

2024-03-13 18:22 UTC, Levitinn approved these changes

2024-03-14 08:56 UTC, merged