feat: solve 3-birthday task
antryabov/homework-js pull request #3
Opened 2024-03-10 10:45 UTC by antryabov

2024-03-10 19:07 UTC, Levitinn requested changes

2024-03-10 19:07 UTC, Levitinn commented on app.js
что то не так. если указать завтрашний день ДР, код возвращает тру. 
пс. твоя строка даты соответствует октябрю месяцу. это намеренно или ты напутал?

2024-03-13 08:03 UTC, antryabov commented on app.js
там дата считается сначала месяц/день/год

2024-03-13 18:20 UTC, Levitinn approved these changes

2024-03-14 08:58 UTC, merged