8 solid
antryabov/homework-js pull request #8
Opened 2024-03-27 11:32 UTC by antryabov

2024-03-31 19:29 UTC, Levitinn requested changes

2024-03-31 19:29 UTC, Levitinn commented on app.js
все твои классы ничего не хранят в себе и ничего не считают. кажется, чего то не хватает

2024-04-01 13:16 UTC, antryabov commented on app.js
Мне немного непонятно, почему, когда я указываю в наследуемом классе выше конструктора amount, а в конструкторе super(amount, hour), к примеру, когда создаем объект и записываем аргументы, то amount будет undefined.

2024-04-03 19:24 UTC, Levitinn approved these changes

2024-04-03 19:33 UTC, closed without merging